### ISSUE TITLE
[BUG] Test ending after typing one character.

### ISSUE THREAD

**Issue by NextStep-IM** [kraanzu/smassh#74] opened 2024-02-05 15:52 UTC
### Describe the bug 🐛

This bug starts occurring after doing the first test at startup. The test ends after typing a character.

### To Reproduce 🐣

1. Start _smassh_.
2. Do a test.
3. Do a test again.

### Screenshots 🧐

[smassh.webm](https://github.com/kraanzu/smassh/assets/140648058/4d2443ae-5982-4fc0-8ec2-f4d37b5176a0)

### Your operating system name

Arco Linux

### Your operating system version

6.7.3-arch1-2

**Comment by SwayKh** [comment] 2024-02-05 15:55
I just Installed this after seeing a post on reddit, Can confirm I am getting this same issue.

Need to close the app and restart again to be able to type again.

**Comment by kraanzu** [comment] 2024-02-05 16:06
Hmm... strange.
How did you install?

**Comment by kraanzu** [comment] 2024-02-05 16:16
> I installed using pipx

Can you check the version using `smassh --version`

I'm not able to reproduce with the latest build

**Comment by NextStep-IM** [comment] 2024-02-05 16:17
> Can you check the version using smassh --version
3.0.4

**Comment by kraanzu** [comment] 2024-02-05 16:20
> Need to close the app and restart again to be able to type again.

According to @SwayKh, he's able to type if he restarts the app. Is that the case for you as well?

**Comment by NextStep-IM** [comment] 2024-02-05 16:21
> Is that the case for you as well?

Yep

**Comment by kraanzu** [comment] 2024-02-05 16:25
Ok one last thing, can you delete the config file and restart the app?

```bash
python -c "import appdirs; print(appdirs.user_data_dir('smassh'))"
```

Should be ~/.config/smassh/smassh.json for you

There are three settings (first three ones) which will end the typing if certain conditions are not met (speed/accuracy) 
Maybe you turned on those :)

![image](https://github.com/kraanzu/smassh/assets/97718086/33872c37-efd3-44f8-b8d3-687db685a359)

**Comment by NextStep-IM** [comment] 2024-02-05 16:32
> There are three settings (first three ones) which will end the typing if certain conditions are not met (speed/accuracy)
Maybe you turned on those :)

Right on target.
This was my config: 
```
{"difficulty": "normal", "blind_mode": false, "min_speed": 2, "min_accuracy": 0, "min_burst": 0, "force_correct": false, "confidence_mode": "off", "capitalization_mode": "off", "cursor_buddy_speed": 0, "tab_reset": false, "language": "english", "numbers": false, "punctuations": false, "mode": "words", "words_count": 30, "time_count": 30, "caret_style": "block", "writing mode": "words", "theme": "catppuccin"}

```
Fresh config after deleting:
```
{"difficulty": "normal", "blind_mode": false, "min_speed": 0, "min_accuracy": 0, "min_burst": 0, "force_correct": false, "confidence_mode": "off", "capitalization_mode": "off", "cursor_buddy_speed": 0, "tab_reset": false, "language": "english", "numbers": false, "punctuations": false, "mode": "words", "words_count": 30, "time_count": 30, "caret_style": "block", "writing mode": "words", "theme": "nord"}

```

**Comment by NextStep-IM** [comment] 2024-02-05 16:34
Thanks a lot, @kraanzu!

**Comment by kraanzu** [comment] 2024-02-05 16:35
Awesome! 
Thing is you have to do a quick start on this one otherwise the calculation done is quite low
Maybe I should add a timeout or something or maybe at least show on result screen that the test ended due to the setting :)

**Comment by kraanzu** [comment] 2024-02-05 16:36
> Seems weird that the setting was enabled by default, 

Nope! Maybe you accidently pressed `tab` key on settings screen :)

**Comment by kraanzu** [comment] 2024-02-05 16:37
Anyways, I'll close this issue now then
Thanks for giving smassh a try :smile: :heart:

**Closed by kraanzu** 2024-02-05 16:37 UTC
Labels: bug

**Comment by kraanzu** [comment] 2024-02-05 16:45
No problemo! I'll fix this so it doesn't end the test that quick :)
